runtime: nodejs20

handlers:
  - url: /static
    static_dir: build/static

  - url: /assets
    static_dir: build/assets

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
