export const industryData = [
    {
      name: 'Retail & Ecommerce',
      title: 'Stop Site-Wide Coupons. Personalize the Nudge.',
      useCases: [
        { title: 'Cart Abandon', description: 'Recover more carts by optimizing coupons, free shipping, or reassurance content — not blasting 10% offs.' },
        { title: 'Checkout Recovery', description: 'Lift checkout conversions by deciding between financing offers, reviews, or urgency nudges — not just defaulting to discounts.' },
        { title: 'Repeat Purchase / Replenishment', description: 'Drive reorders by personalizing bundles, subscriptions, or loyalty credits — not blanket replenishment emails.' },
        { title: 'High-AOV Reassurance', description: 'Protect margin on big baskets by testing warranties, social proof, or financing — not giving away unnecessary discounts.' },
        { title: 'Seasonal Promotions', description: 'Stretch promo budgets by allocating bundles, loyalty perks, or exclusive drops per user — not site-wide coupon blasts.' },
      ],
      personas: [
        {
          name: 'Emily Carter', role: 'Acquisition · First visit (Value Seeker)',
          image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days of week', value: 'Monday · Wednesday · Saturday' },
            { label: 'Frequency', value: '2× week' },
            { label: 'Time of day', value: '10:20 AM' },
            { label: 'Creative', value: 'Value comparison + size/fit UGC (similar body type)' },
            { label: 'Product pick', value: 'Pre-sized value bundle (core item + low-cost accessory)' },
            { label: 'Offer', value: '$10 off or Free Shipping on exit-intent only' },
            { label: 'Channel', value: 'On-site + SMS (if opted-in)' },
          ],
        },
        {
          name: 'Jordan Lee', role: 'Checkout · Trust-seeker at payment',
          image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days of week', value: 'Tuesday · Friday' },
            { label: 'Frequency', value: '2× week' },
            { label: 'Time of day', value: '7:47 PM' },
            { label: 'Creative', value: '“Free 30-day returns, instant refunds; delivery date shown.”' },
            { label: 'Product pick', value: 'Keep cart; suggest low-return add-on (care kit)' },
            { label: 'Offer', value: 'Free 2-Day Shipping when paying today' },
            { label: 'Channel', value: 'Email + On-site checkout panel' },
          ],
        },
        {
          name: 'Marcus Reed', role: 'Win-back · 120-day lapsed (High-AOV)',
          image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days of week', value: 'Tuesday' },
            { label: 'Frequency', value: 'Weekly' },
            { label: 'Time of day', value: '3:42 PM' },
            { label: 'Creative', value: '“New drop that matches your last pick' },
            { label: 'Product pick', value: 'Curated 3-item set (flagship, mid-tier, accessory) in prior size/color' },
            { label: 'Offer', value: '20% off accessory when cart ≥ $120' },
            { label: 'Channel', value: 'Email → SMS fallback → on-site hero swap on return' },
          ],
        },
      ],
    },
    {
      name: 'Travel',
      title: 'Personalization That Changes How People Choose to Fly',
      useCases: [
        { title: 'Booking Abandon', description: 'Recover bookings by deciding voucher vs miles vs urgency hold — not batch voucher blasts.' },
        { title: 'Loyalty Tier Campaigns', description: 'Lift engagement with tailored bonus miles, upgrades, or lounge passes — not generic tier emails.' },
        { title: 'Disruption Compensation', description: 'Cut comp costs by optimizing refunds, miles, or future-trip vouchers per passenger — not leaving it to agent discretion.' },
        { title: 'Upsells (Seats, Bags, Ancillaries)', description: 'Grow ancillary revenue by targeting seat upgrades, baggage offers, or meal add-ons — not showing every upsell to everyone.' },
        { title: 'Lapsed Loyalty Members', description: 'Re-engage members with bonus miles, partner perks, or vouchers — not a single win-back offer.' },
      ],
      personas: [
        {
          name: 'Sophia Nguyen', role: 'Booking abandoner · Economy leisure traveler',
          image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Monday · Thursday' },
            { label: 'Frequency', value: '1× week' },
            { label: 'Time', value: '6:30 PM' },
            { label: 'Creative', value: '“Fares expiring—secure your seat now.”' },
            { label: 'Product pick', value: 'Same itinerary, cheaper return variant' },
            { label: 'Offer', value: '500 miles bonus OR $20 voucher if booked today' },
            { label: 'Channel', value: 'Email → Push' },
          ],
        },
        {
          name: 'David Romero', role: 'Disruption · Frequent flyer (Tier Silver)',
          image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Event-driven (flight delay/cancel)' },
            { label: 'Frequency', value: 'Real-time' },
            { label: 'Time', value: 'N/A' },
            { label: 'Creative', value: '“Sorry for the disruption, your loyalty matters.”' },
            { label: 'Product pick', value: 'Same flight → rebook option shown first' },
            { label: 'Offer', value: 'Choice of $50 voucher, 1K bonus miles, or lounge pass' },
            { label: 'Channel', value: 'SMS + App push' },
          ],
        },
        {
          name: 'Isabelle Laurent', role: 'Loyalty engagement · Near tier upgrade',
          image: 'https://images.unsplash.com/photo-1491349174775-aaafddd81942?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Tuesday · Friday' },
            { label: 'Frequency', value: '1× week' },
            { label: 'Time', value: '9:05 AM' },
            { label: 'Creative', value: '“You’re 2 flights away from Gold—unlock lounge & upgrades.”' },
            { label: 'Product pick', value: 'Suggested weekend getaway deal' },
            { label: 'Offer', value: '2x miles booster OR status accelerator promo' },
            { label: 'Channel', value: 'Email + App inbox' },
          ],
        },
      ],
    },
    {
      name: 'Hospitality',
      title: 'End-to-End Hotel Personalization, Not One-Size-Fits-All',
      useCases: [
        { title: 'Cancellation Save', description: 'Recover cancellations by deciding between points, upgrades, or future-stay vouchers — not default refunds.' },
        { title: 'Loyalty Renewal', description: 'Increase renewals with tailored bonus nights, upgrades, or experiences — not global point offers.' },
        { title: 'Complaint Resolution', description: 'Protect comp budgets by optimizing points, amenity credits, or upgrades per guest — not staff gut feel.' },
        { title: 'Upsell Campaigns', description: 'Boost ARPU with room upgrades, amenity packages, or bundled experiences — not generic add-ons.' },
        { title: 'Direct Booking Incentives', description: 'Grow direct bookings by deciding between upgrades, loyalty multipliers, or amenity perks — not blanket discounts.' },
      ],
      personas: [
        {
          name: 'Michael O’Connor', role: 'Cancellation risk · Business traveler',
          image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: '48 hours pre-stay' },
            { label: 'Frequency', value: 'Once per booking' },
            { label: 'Time', value: '11:00 AM' },
            { label: 'Creative', value: '“Flexible change at no fee + free breakfast included.”' },
            { label: 'Product pick', value: 'Same booking, business rate' },
            { label: 'Offer', value: 'Free breakfast upgrade (instead of refund risk)' },
            { label: 'Channel', value: 'Email + App push' },
          ],
        },
        {
          name: 'Anita Patel', role: 'Loyalty renewal · Elite tier member',
          image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Thursday' },
            { label: 'Frequency', value: '1× month before expiry' },
            { label: 'Time', value: '7:20 PM' },
            { label: 'Creative', value: '“Renew Gold and keep suite upgrades rolling.”' },
            { label: 'Product pick', value: 'Partner resort package' },
            { label: 'Offer', value: '5K bonus points or 1 free night with renewal' },
            { label: 'Channel', value: 'Email → Call center follow-up' },
          ],
        },
        {
          name: 'Jonas Müller', role: 'Complaint resolution · Family guest',
          image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Event-driven (complaint logged)' },
            { label: 'Frequency', value: '1× post-incident' },
            { label: 'Time', value: 'Within 24 hrs' },
            { label: 'Creative', value: '“We’re sorry your stay wasn’t perfect—let us make it right.”' },
            { label: 'Product pick', value: 'Next booking offer for same room type' },
            { label: 'Offer', value: '10K points OR spa voucher (choose)' },
            { label: 'Channel', value: 'SMS → Email' },
          ],
        },
      ],
    },
    {
      name: 'Gaming',
      title: 'The Right Perk, Right Player, Right Time',
      useCases: [
        { title: 'Lapsed Player Comeback', description: 'Recover lapsed players with comeback bundles, bonus currency, or skins — not one default offer.' },
        { title: 'Whale Retention', description: 'Protect ARPU by tailoring VIP bundles, exclusive skins, or perks per whale — not uniform VIP promos.' },
        { title: 'New Player Onboarding', description: 'Convert faster with starter bundles, free trials, or unlocks — not one starter pack for all.' },
        { title: 'Event Pass Campaigns', description: 'Increase pass uptake by testing discounts, free trials, or exclusive event perks — not a single pass offer.' },
        { title: 'In-Session Churn Saves', description: 'Stop rage-quit churn with free boosts, skips, or reassurance nudges — not static defeat offers.' },
      ],
      personas: [
        {
          name: 'Tyrell Jackson', role: 'Lapsed player · 14 days inactive (mid-spender)',
          image: 'https://images.unsplash.com/photo-1615109398623-88346a601842?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Tuesday' },
            { label: 'Frequency', value: '1× week' },
            { label: 'Time', value: '8:00 PM' },
            { label: 'Creative', value: '“Come back—your clan needs you.”' },
            { label: 'Product pick', value: 'Comeback bundle (gems + boost)' },
            { label: 'Offer', value: 'Free skin OR 20% bundle discount' },
            { label: 'Channel', value: 'Push + In-app store slot' },
          ],
        },
        {
          name: 'Anna Petrova', role: 'Whale · High ARPU VIP',
          image: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Friday' },
            { label: 'Frequency', value: 'Event-driven + 1× week' },
            { label: 'Time', value: '9:30 PM' },
            { label: 'Creative', value: '“Exclusive for you: early unlock skin.”' },
            { label: 'Product pick', value: 'VIP-only cosmetic bundle' },
            { label: 'Offer', value: 'Exclusive cosmetic OR 2x currency booster' },
            { label: 'Channel', value: 'In-app inbox + Email' },
          ],
        },
        {
          name: 'Liam Wright', role: 'Newbie · Day 3 session',
          image: 'https://images.unsplash.com/photo-1628157588553-5ee30a684123?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Daily (on login)' },
            { label: 'Frequency', value: '1×' },
            { label: 'Time', value: '10:15 AM' },
            { label: 'Creative', value: '“Upgrade now to unlock faster progress.”' },
            { label: 'Product pick', value: 'Starter bundle (weapon + currency)' },
            { label: 'Offer', value: '50% off starter OR free trial currency' },
            { label: 'Channel', value: 'Onboarding pop-up' },
          ],
        },
      ],
    },
    {
      name: 'Consumer Apps',
      title: 'Personalization That Changes How People Subscribe',
      useCases: [
        { title: 'Trial → Paid Conversion', description: 'Shorten CAC payback by deciding whether to extend, discount, upsell annual, or just reassure each trial user.' },
        { title: 'Churn Save (Cancellation Flow)', description: 'Retain more users by optimizing pause, discount, or feature unlocks per cancel attempt — not blanket 20% offs.' },
        { title: 'Win-Back Campaign', description: 'Re-activate dormant users by picking the right lever — extension, discount, or feature highlight — for each.' },
        { title: 'Upsell / Cross-Sell', description: 'Boost ARPU by personalizing annual, family, or bundle offers instead of spamming every subscriber.' },
        { title: 'Engagement Reactivation', description: 'Drive daily activity by mixing nudges, streak extensions, or free unlocks — not just repetitive reminders.' },
      ],
      personas: [
        {
          name: 'Rachel Gomez', role: 'Trial user · Day 6',
          image: 'https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Day 6' },
            { label: 'Frequency', value: 'Once' },
            { label: 'Time', value: '7:10 PM' },
            { label: 'Creative', value: '“Your trial is almost up—don’t lose your progress.”' },
            { label: 'Product pick', value: 'Same plan, annual highlighted' },
            { label: 'Offer', value: 'Extend trial 7 days OR 20% off annual' },
            { label: 'Channel', value: 'Email + Push' },
          ],
        },
        {
          name: 'Omar Ali', role: 'Cancellation · Pauser',
          image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Event-driven (cancel click)' },
            { label: 'Frequency', value: 'Once per cancel flow' },
            { label: 'Time', value: 'N/A' },
            { label: 'Creative', value: '“Take a pause instead of leaving—your streak is safe.”' },
            { label: 'Product pick', value: 'Same subscription paused' },
            { label: 'Offer', value: 'Pause for 2 months OR 10% discount if staying' },
            { label: 'Channel', value: 'In-app + Email' },
          ],
        },
        {
          name: 'Sofia Rossi', role: 'Win-back · 60-day inactive',
          image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=250&h=250&auto=format&fit=crop',
          details: [
            { label: 'Days', value: 'Tuesday' },
            { label: 'Frequency', value: '1× week for 3 weeks' },
            { label: 'Time', value: '11:20 AM' },
            { label: 'Creative', value: '“New guided program matches your last goals.”' },
            { label: 'Product pick', value: 'Updated feature set (new classes/tracks)' },
            { label: 'Offer', value: 'Free 7-day unlock OR $5 credit' },
            { label: 'Channel', value: 'Email → Push fallback' },
          ],
        },
      ],
    },
  ];
  